---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operatorfwk.felipe88alves
  resources:
  - products
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operatorfwk.felipe88alves
  resources:
  - products/finalizers
  verbs:
  - update
- apiGroups:
  - operatorfwk.felipe88alves
  resources:
  - products/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operatorfwk.felipe88alves
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operatorfwk.felipe88alves
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - operatorfwk.felipe88alves
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
